### ISSUE TITLE
question of understanding

### ISSUE THREAD

**Issue by sfritzsche** [hryvinskyi/magento2-invisible-captcha#9]
Hi @hryvinskyi 

in the last few days, have been investigating issues with the Recaptcha (V3) related to the Ajax login for a larger project and found that the default implementation within Magento is not working very reliably.

Specifically, we are talking about the Ajax form (knockout submit binding) not containing the desired security key in some cases and thus the validation fails in the controller.

Subsequently, I came across your module.

At the moment I'm stuck considering switching to your module. 

At the moment we are using standard forms (customer_login, customer_forgot_password, customer_create, contact, ajax login) as well as some third party forms (Aheadworks, Amasty, ...) and self-developed forms (ajax register, ...).

Having roughly surveyed the module, I'm assuming that it's probably best to disable all core ReCaptcha functions so that you can take full advantage of the lazy-loading benefits of this module. 

So if we were to do it this way, we would only need to upgrade to the "Hryvinskyi_InvisibleCaptcha/js/invisible-captcha" component you developed for all third-party modules (these mostly use & extend the Core-ReCaptcha functions) and for all self-developed modules (as well).

At this point, however, I was wondering if it wouldn't have been much more sensible or easier if you, instead of a parallel system (system setting, layout instructions, JS component) would have simply overridden the Core-ReCaptcha-JS component ? Then all third-party modules or even all custom modules that use the Core-ReCaptcha functionality would also run automatically with your optimizations.

Regards,

Steven

**Comment by hryvinskyi** [comment]
Hi @sfritzsche, sorry for the long reply

You have asked a good question, I thought about it before, but the problem is to support different versions of Magento
for example, before, magento did not have its own recaptcha module
after that, magento added a this (https://github.com/magespecialist/m2-MSP_ReCaptcha) third-party recapture module to the core 
and from 2.3 version magento added new separated modules recaptcha (https://github.com/magento/security-package)

in the future I plan to add a separate module that will disable the default magento recap functionality, and substitute a new one from this module

Thanks
